# Generated by Django 5.1.7 on 2025-03-27 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=False)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('academic_year', models.CharField(default='2024/2025', max_length=9)),
            ],
        ),
        migrations.CreateModel(
            name='FundAllocationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('total_funds', models.FloatField()),
            ],
        ),
    ]
